const AUTH_URL: &str = "https://id.twitch.tv/oauth2/authorize";

pub const SCOPES: [&str; 55] = [
    "analytics:read:extensions",
    "analytics:read:games",
    "bits:read",
    "channel:edit:commercial",
    "channel:manage:broadcast",
    "channel:read:charity",
    "channel:manage:extensions",
    "channel:manage:moderators",
    "channel:manage:polls",
    "channel:manage:predictions",
    "channel:manage:raids",
    "channel:manage:redemptions",
    "channel:manage:schedule",
    "channel:manage:videos",
    "channel:manage:vips",
    "channel:moderate",
    "channel:manage:redemptions",
    "channel:read:editors",
    "channel:read:goals",
    "channel:read:hype_train",
    "channel:read:polls",
    "channel:read:predictions",
    "channel:read:redemptions",
    "channel:read:stream_key",
    "channel:read:subscriptions",
    "channel:read:vips",
    "chat:edit",
    "chat:read",
    "clips:edit",
    "moderation:read",
    "moderator:manage:announcements",
    "moderator:manage:automod_settings",
    "moderator:manage:banned_users",
    "moderator:manage:chat_messages",
    "moderator:manage:chat_settings",
    "moderator:manage:shield_mode",
    "moderator:manage:shoutouts",
    "moderator:read:automod_settings",
    "moderator:read:blocked_terms",
    "moderator:read:chat_settings",
    "moderator:read:chatters",
    "moderator:read:followers",
    "moderator:read:shield_mode",
    "moderator:read:shoutouts",
    "user:edit",
    "user:manage:blocked_users",
    "user:manage:chat_color",
    "user:manage:whispers",
    "user:read:blocked_users",
    "user:read:broadcast",
    "user:read:email",
    "user:read:follows",
    "user:read:subscriptions",
    "whispers:read",
    "whispers:edit",
];

pub fn oauth2_url(
    client_id: &str,
    redirect_uri: &str,
    scopes: Vec<&str>,
    force_verify: bool,
    state: &str,
) -> String {
    let params = vec![
        format!("client_id={client_id}"),
        format!("redirect_uri={redirect_uri}"),
        format!("scope={}", urlencoding::encode(&scopes.join(" "))),
        format!("response_type=code"),
        format!("force_verify={force_verify}"),
        format!("state={}", urlencoding::encode(state)),
    ]
    .join("&");

    format!("{AUTH_URL}?{}", params)
}
