[workspace]
resolver = "2"
members = ["apps/desktop/src-tauri", "crates/*"]

[patch.crates-io]
rspc = { git = "https://github.com/oscartbeaumont/rspc", rev = "799eec5df7533edf331f41d3f1be03de07e038d7" }
