packages:
  - interface
  - apps/*
  - crates/*
  - packages/*

patchedDependencies:
  vite-plugin-solid: patches/vite-plugin-solid.patch
  "@effect/platform-node-shared": patches/@effect__platform-node-shared.patch
