/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {};
declare global {
	const IconBiX: typeof import("~icons/bi/x.jsx")["default"];
	const IconLineMdChevronDown: typeof import("~icons/line-md/chevron-down.jsx")["default"];
	const IconLineMdChevronSmallDown: typeof import("~icons/line-md/chevron-small-down.jsx")["default"];
	const IconLucideChevronDown: typeof import("~icons/lucide/chevron-down.jsx")["default"];
	const IconLucideChevronRight: typeof import("~icons/lucide/chevron-right.jsx")["default"];
	const IconMaterialSymbolsAddRounded: typeof import("~icons/material-symbols/add-rounded.jsx")["default"];
	const IconMaterialSymbolsDeleteOutline: typeof import("~icons/material-symbols/delete-outline.jsx")["default"];
}
