/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconAntDesignCheckOutlined: typeof import('~icons/ant-design/check-outlined.jsx')['default']
  const IconAntDesignCloseOutlined: typeof import('~icons/ant-design/close-outlined.jsx')['default']
  const IconAntDesignDeleteOutlined: typeof import('~icons/ant-design/delete-outlined.jsx')['default']
  const IconAntDesignEditOutlined: typeof import('~icons/ant-design/edit-outlined.jsx')['default']
  const IconBiX: typeof import('~icons/bi/x.jsx')['default']
  const IconBxsBone: typeof import('~icons/bxs/bone.jsx')['default']
  const IconFa6SolidChevronRight: typeof import('~icons/fa6-solid/chevron-right.jsx')['default']
  const IconFaSolidSave: typeof import('~icons/fa-solid/save.jsx')['default']
  const IconGgImport: typeof import('~icons/gg/import.jsx')['default']
  const IconGravityUiPlugConnection: typeof import('~icons/gravity-ui/plug-connection.jsx')['default']
  const IconHeroiconsXMarkSolid: typeof import('~icons/heroicons/x-mark-solid.jsx')['default']
  const IconMaterialSymbolsAddRounded: typeof import('~icons/material-symbols/add-rounded.jsx')['default']
  const IconMdiConnection: typeof import('~icons/mdi/connection.jsx')['default']
  const IconPhExport: typeof import('~icons/ph/export.jsx')['default']
  const IconRadixIconsExternalLink: typeof import('~icons/radix-icons/external-link.jsx')['default']
  const IconTablerCheck: typeof import('~icons/tabler/check.jsx')['default']
  const IconTablerChevronDown: typeof import('~icons/tabler/chevron-down.jsx')['default']
  const IconTablerChevronRight: typeof import('~icons/tabler/chevron-right.jsx')['default']
  const IconTablerCircle: typeof import('~icons/tabler/circle.jsx')['default']
  const IconTablerClipboard: typeof import('~icons/tabler/clipboard.jsx')['default']
  const IconTablerCopy: typeof import('~icons/tabler/copy.jsx')['default']
  const IconTdesignFolderImport: typeof import('~icons/tdesign/folder-import.jsx')['default']
}
