// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "fs.list", input: string, result: Entry[] },
    mutations: 
        { key: "oauth.authorize", input: string, result: any | null },
    subscriptions: 
        { key: "websocket.server", input: number, result: string }
};

export type Entry = { Dir: string } | { File: string }
