/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {};
declare global {
	const IconTablerChevronDown: typeof import("~icons/tabler/chevron-down.jsx")["default"];
	const IconTablerDeviceDesktopDown: typeof import("~icons/tabler/device-desktop-down.jsx")["default"];
	const IconTablerSandbox: typeof import("~icons/tabler/sandbox.jsx")["default"];
}
