/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconAntDesignDeleteOutlined: typeof import('~icons/ant-design/delete-outlined.jsx')['default']
  const IconAntDesignEditOutlined: typeof import('~icons/ant-design/edit-outlined.jsx')['default']
  const IconBiX: typeof import('~icons/bi/x.jsx')['default']
  const IconFaSolidSave: typeof import('~icons/fa-solid/save.jsx')['default']
  const IconGgImport: typeof import('~icons/gg/import.jsx')['default']
  const IconGravityUiPlugConnection: typeof import('~icons/gravity-ui/plug-connection.jsx')['default']
  const IconHeroiconsXMarkSolid: typeof import('~icons/heroicons/x-mark-solid.jsx')['default']
  const IconMaterialSymbolsAddRounded: typeof import('~icons/material-symbols/add-rounded.jsx')['default']
  const IconMaterialSymbolsArrowDropDownRounded: typeof import('~icons/material-symbols/arrow-drop-down-rounded.jsx')['default']
  const IconMaterialSymbolsArrowDropUpRounded: typeof import('~icons/material-symbols/arrow-drop-up-rounded.jsx')['default']
  const IconMaterialSymbolsArrowRightRounded: typeof import('~icons/material-symbols/arrow-right-rounded.jsx')['default']
  const IconMaterialSymbolsDragIndicator: typeof import('~icons/material-symbols/drag-indicator.jsx')['default']
  const IconMaterialSymbolsDragIndicatorRounded: typeof import('~icons/material-symbols/drag-indicator-rounded.jsx')['default']
  const IconMaterialSymbolsEdit: typeof import('~icons/material-symbols/edit.jsx')['default']
  const IconMaterialSymbolsEditRounded: typeof import('~icons/material-symbols/edit-rounded.jsx')['default']
  const IconMdiConnection: typeof import('~icons/mdi/connection.jsx')['default']
  const IconMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal.jsx')['default']
  const IconOcticonProjectSymlink16: typeof import('~icons/octicon/project-symlink16.jsx')['default']
  const IconSystemUiconsReset: typeof import('~icons/system-uicons/reset.jsx')['default']
  const IconTablerCheck: typeof import('~icons/tabler/check.jsx')['default']
  const IconTablerChevronRight: typeof import('~icons/tabler/chevron-right.jsx')['default']
  const IconTablerCircle: typeof import('~icons/tabler/circle.jsx')['default']
  const IconTablerColumns: typeof import('~icons/tabler/columns.jsx')['default']
  const IconTablerCopy: typeof import('~icons/tabler/copy.jsx')['default']
  const IconTablerSettings: typeof import('~icons/tabler/settings.jsx')['default']
  const IconTdesignFolderImport: typeof import('~icons/tdesign/folder-import.jsx')['default']
}
