/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconAntDesignCheckOutlined: typeof import('~icons/ant-design/check-outlined.jsx')['default']
  const IconAntDesignCloseOutlined: typeof import('~icons/ant-design/close-outlined.jsx')['default']
  const IconAntDesignDeleteOutlined: typeof import('~icons/ant-design/delete-outlined.jsx')['default']
  const IconAntDesignEditOutlined: typeof import('~icons/ant-design/edit-outlined.jsx')['default']
  const IconBiX: typeof import('~icons/bi/x.jsx')['default']
  const IconBxReset: typeof import('~icons/bx/reset.jsx')['default']
  const IconFa6SolidChevronRight: typeof import('~icons/fa6-solid/chevron-right.jsx')['default']
  const IconFaSolidSave: typeof import('~icons/fa-solid/save.jsx')['default']
  const IconGgImport: typeof import('~icons/gg/import.jsx')['default']
  const IconGravityUiPlugConnection: typeof import('~icons/gravity-ui/plug-connection.jsx')['default']
  const IconHeroiconsXMarkSolid: typeof import('~icons/heroicons/x-mark-solid.jsx')['default']
  const IconMaterialSymbolsAddRounded: typeof import('~icons/material-symbols/add-rounded.jsx')['default']
  const IconMaterialSymbolsArrowDownRounded: typeof import('~icons/material-symbols/arrow-down-rounded.jsx')['default']
  const IconMaterialSymbolsArrowRightRounded: typeof import('~icons/material-symbols/arrow-right-rounded.jsx')['default']
  const IconMaterialSymbolsExpandMoreRounded: typeof import('~icons/material-symbols/expand-more-rounded.jsx')['default']
  const IconMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal.jsx')['default']
  const IconPhExport: typeof import('~icons/ph/export.jsx')['default']
  const IconSystemUiconsReset: typeof import('~icons/system-uicons/reset.jsx')['default']
  const IconTablerCheck: typeof import('~icons/tabler/check.jsx')['default']
  const IconTablerChevronRight: typeof import('~icons/tabler/chevron-right.jsx')['default']
  const IconTablerCircle: typeof import('~icons/tabler/circle.jsx')['default']
  const IconTablerCopy: typeof import('~icons/tabler/copy.jsx')['default']
  const IconTdesignFolderImport: typeof import('~icons/tdesign/folder-import.jsx')['default']
}
