[package]
name = "regex-syntax-wasm"
description = "A WebAssembly version of the regex-syntax crate"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
regex-syntax = "0.8.4"
wasm-bindgen = "0.2.93"
