// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "fs.list", input: string, result: Entry[] },
    mutations: 
        { key: "websocket.send", input: { port: number; client: number | null; data: string }, result: null },
    subscriptions: 
        { key: "oauth.authorize", input: string, result: any | null } | 
        { key: "websocket.server", input: number, result: [number, Message] }
};

export type Entry = { Dir: string } | { File: string }

export type Message = { Text: string } | "Connected" | "Disconnected"
