/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function crashLogAppend(kind: string, message: string) {
    return invoke()<null>("crash_log_append", { kind, message })
}

export function crashLogPath() {
    return invoke()<string>("crash_log_path", {})
}

/**
 * File size in bytes (Tauri 1.x JS fs API has no metadata helper).
 */
export function fileSize(path: string) {
    return invoke()<number>("file_size", { path })
}

export function fetch(method: string, url: string, headers: ([string, string])[], data: number[] | null, connectTimeout: number | null, maxRedirections: number | null) {
    return invoke()<number>("fetch", { method,url,headers,data,connectTimeout,maxRedirections })
}

/**
 * POST multipart/form-data with an optional file streamed from disk (avoids loading
 * large files into the JS runtime before upload).
 */
export function fetchMultipart(url: string, headers: ([string, string])[], fields: ([string, string])[], filePath: string | null, fileFieldName: string | null, connectTimeout: number | null) {
    return invoke()<number>("fetch_multipart", { url,headers,fields,filePath,fileFieldName,connectTimeout })
}

export function fetchCancel(rid: number) {
    return invoke()<null>("fetch_cancel", { rid })
}

export function fetchSend(rid: number) {
    return invoke()<FetchResponse>("fetch_send", { rid })
}

export function fetchReadBody(rid: number) {
    return invoke()<number[]>("fetch_read_body", { rid })
}

export type FetchResponse = { status: number; statusText: string; headers: ([string, string])[]; url: string }
