/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

/**
 * Append a line from the webview (uncaught errors, unhandled rejections).
 */
export function crashLogAppend(kind: string, message: string) {
    return invoke()<null>("crash_log_append", { kind,message })
}

/**
 * Path to `crash.log` for support / debugging.
 */
export function crashLogPath() {
    return invoke()<string>("crash_log_path")
}

/**
 * File size in bytes (Tauri 1.x JS fs API has no metadata helper).
 */
export function fileSize(path: string) {
    return invoke()<number>("file_size", { path })
}

export function enumerateAudioOutputs() {
    return invoke()<AudioOutputDevice[]>("enumerate_audio_outputs")
}

export function playAudio(path: string, deviceName: string | null) {
    return invoke()<PlayResult>("play_audio", { path,deviceName })
}

export function stopAudio(id: string) {
    return invoke()<null>("stop_audio", { id })
}

export function setAudioVolume(id: string, volume: number) {
    return invoke()<null>("set_audio_volume", { id,volume })
}

export function stopAllAudio() {
    return invoke()<null>("stop_all_audio")
}

export function fetch(method: string, url: string, headers: ([string, string])[], data: number[] | null, connectTimeout: number | null, maxRedirections: number | null) {
    return invoke()<number>("fetch", { method,url,headers,data,connectTimeout,maxRedirections })
}

/**
 * POST multipart/form-data with an optional file streamed from disk (avoids loading
 * large files into the JS runtime before upload).
 */
export function fetchMultipart(url: string, headers: ([string, string])[], fields: ([string, string])[], filePath: string | null, fileFieldName: string | null, connectTimeout: number | null) {
    return invoke()<number>("fetch_multipart", { url,headers,fields,filePath,fileFieldName,connectTimeout })
}

export function fetchCancel(rid: number) {
    return invoke()<null>("fetch_cancel", { rid })
}

export function fetchSend(rid: number) {
    return invoke()<FetchResponse>("fetch_send", { rid })
}

export function fetchReadBody(rid: number) {
    return invoke()<number[]>("fetch_read_body", { rid })
}

export type AudioOutputDevice = { device_id: string; label: string }
export type FetchResponse = { status: number; statusText: string; headers: ([string, string])[]; url: string }
export type PlayResult = { id: string }
