name: Install desktop-specific dependencies
description: Installs desktop-specific dependencies for the current platform
runs:
    using: "composite"
    steps:
        - name: install dependencies (ubuntu only)
          if: matrix.platform == 'ubuntu-20.04'
          shell: bash
          run: |
              sudo apt-get update
              sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev libxtst-dev libevdev-dev libxdo-dev
