[package]
name = "deno_experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# deno_runtime = "0.157.0"
tokio = { version = "1.37.0", features = ["macros"] }
