// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "fs.list", input: string, result: Entry[] },
    mutations: never,
    subscriptions: 
        { key: "oauth.authorize", input: string, result: any | null } | 
        { key: "websocket.server", input: number, result: Message }
};

export type Message = { Text: string } | "Connected" | "Disconnected"

export type Entry = { Dir: string } | { File: string }
