/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconAntDesignDeleteOutlined: typeof import('~icons/ant-design/delete-outlined.jsx').default
  const IconAntDesignEditOutlined: typeof import('~icons/ant-design/edit-outlined.jsx').default
  const IconBiX: typeof import('~icons/bi/x.jsx').default
  const IconGgImport: typeof import('~icons/gg/import.jsx').default
  const IconGgSpinner: typeof import('~icons/gg/spinner.jsx').default
  const IconGravityUiPlugConnection: typeof import('~icons/gravity-ui/plug-connection.jsx').default
  const IconHeroiconsXMarkSolid: typeof import('~icons/heroicons/x-mark-solid.jsx').default
  const IconIcBaselineDiscord: typeof import('~icons/ic/baseline-discord.jsx').default
  const IconIcRoundShare: typeof import('~icons/ic/round-share.jsx').default
  const IconMaterialSymbolsAddRounded: typeof import('~icons/material-symbols/add-rounded.jsx').default
  const IconMaterialSymbolsArrowDropDownRounded: typeof import('~icons/material-symbols/arrow-drop-down-rounded.jsx').default
  const IconMaterialSymbolsArrowDropUpRounded: typeof import('~icons/material-symbols/arrow-drop-up-rounded.jsx').default
  const IconMaterialSymbolsArrowRight: typeof import('~icons/material-symbols/arrow-right.jsx').default
  const IconMaterialSymbolsArrowRightRounded: typeof import('~icons/material-symbols/arrow-right-rounded.jsx').default
  const IconMaterialSymbolsDeleteOutline: typeof import('~icons/material-symbols/delete-outline.jsx').default
  const IconMdiDotsHorizontal: typeof import('~icons/mdi/dots-horizontal.jsx').default
  const IconMdiGithub: typeof import('~icons/mdi/github.jsx').default
  const IconOcticonProjectSymlink16: typeof import('~icons/octicon/project-symlink16.jsx').default
  const IconPhExport: typeof import('~icons/ph/export.jsx').default
  const IconRadixIconsExternalLink: typeof import('~icons/radix-icons/external-link.jsx').default
  const IconRiTwitterXFill: typeof import('~icons/ri/twitter-x-fill.jsx').default
  const IconSvgSpinners90Ring: typeof import('~icons/svg-spinners/90-ring.jsx').default
  const IconSystemUiconsReset: typeof import('~icons/system-uicons/reset.jsx').default
  const IconTablerCheck: typeof import('~icons/tabler/check.jsx').default
  const IconTablerChevronDown: typeof import('~icons/tabler/chevron-down.jsx').default
  const IconTablerChevronRight: typeof import('~icons/tabler/chevron-right.jsx').default
  const IconTablerCircle: typeof import('~icons/tabler/circle.jsx').default
  const IconTablerCopy: typeof import('~icons/tabler/copy.jsx').default
  const IconTablerDeviceDesktopDown: typeof import('~icons/tabler/device-desktop-down.jsx').default
  const IconTablerSandbox: typeof import('~icons/tabler/sandbox.jsx').default
  const IconTablerSettings: typeof import('~icons/tabler/settings.jsx').default
}
