/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {};
declare global {
	const IconBiX: typeof import("~icons/bi/x.jsx").default;
	const IconGgSpinner: typeof import("~icons/gg/spinner.jsx").default;
	const IconLucideChevronDown: typeof import("~icons/lucide/chevron-down.jsx").default;
	const IconMaterialSymbolsArrowRightRounded: typeof import("~icons/material-symbols/arrow-right-rounded.jsx").default;
	const IconMaterialSymbolsDeleteOutline: typeof import("~icons/material-symbols/delete-outline.jsx").default;
	const IconPhSquareSplitHorizontal: typeof import("~icons/ph/square-split-horizontal.jsx").default;
	const IconTablerArrowsDiagonal: typeof import("~icons/tabler/arrows-diagonal.jsx").default;
	const IconTablerArrowsDiagonalMinimize2: typeof import("~icons/tabler/arrows-diagonal-minimize2.jsx").default;
	const IconTablerCheck: typeof import("~icons/tabler/check.jsx").default;
	const IconTablerChevronRight: typeof import("~icons/tabler/chevron-right.jsx").default;
	const IconTablerCircle: typeof import("~icons/tabler/circle.jsx").default;
}
