# This workflow _produces_ caches which are used to speed up pull request builds.
# Originally from https://github.com/libp2p/rust-libp2p/blob/master/.github/workflows/cache-factory.yml

name: Cache Factory

on:
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    make_cache:
        name: "Make Cache"
        runs-on: ${{ matrix.platform }}
        strategy:
            fail-fast: true
            matrix:
                platform: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-rust

            - uses: ./.github/actions/install-desktop-deps

            - run: mkdir apps/desktop/dist

            - name: Compile (debug)
              run: cargo test --workspace --all-features --no-run

            - name: Compile (release)
              run: cargo test --workspace --all-features --no-run --release
