# This workflow _produces_ caches which are used to speed up pull request builds.
# Originally from https://github.com/libp2p/rust-libp2p/blob/master/.github/workflows/cache-factory.yml

name: Cache Factory

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make_cache:
    name: "Make Cache"
    runs-on: ${{ matrix.settings.host }}
    strategy:
      fail-fast: true
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-rust
        with:
          save-cache: "true"
          target: ${{ matrix.settings.target }}

      - uses: ./.github/actions/install-desktop-deps

      - run: mkdir apps/desktop/dist

      - name: Compile (debug)
        run: cargo test -p macrograph --all-features --no-run --target ${{ matrix.settings.target }}

      - name: Compile (release)
        run: cargo test -p macrograph --all-features --no-run --target ${{ matrix.settings.target }} --release
