name: "CI"
on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    build-desktop:
        strategy:
            fail-fast: false
            matrix:
                settings:
                    - host: macos-latest
                      target: x86_64-apple-darwin
                    - host: macos-latest
                      target: aarch64-apple-darwin
                    - host: windows-latest
                      target: x86_64-pc-windows-msvc
                    - host: ubuntu-latest
                      target: x86_64-unknown-linux-gnu

        runs-on: ${{ matrix.settings.host }}
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-js

            - uses: ./.github/actions/setup-rust
              with:
                  target: ${{ matrix.settings.target }}

            - name: Install desktop deps
              uses: ./.github/actions/install-desktop-deps

            - run: mkdir apps/desktop/dist

            - run: |
                  pnpm desktop tauri build --ci
              env:
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

            - uses: actions/upload-artifact@v3
              with:
                  name: artifacts-${{ matrix.settings.target }}
                  path: ./target/release/bundle/*

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-js

            - name: Run tests
              run: pnpm test

    types:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-js

            - name: pnpm tsc -b

    migrate-db:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: ./.github/actions/setup-js

            - name: Migrate Database
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
                  NODE_ENV: development
              run: pnpm web db:deploy
