name: "CI"
on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    test-tauri:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

            - name: Cache Rust Dependencies
              uses: Swatinem/rust-cache@v2
              with:
                  shared-key: rust-deps
                  save-if: false

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: install frontend dependencies
              run: pnpm install # change this to npm or pnpm depending on which one you use

            - name: Build frontend
              run: pnpm app build

            - uses: JonasKruckenberg/tauri-build@v1
              id: tauri_build
              with:
                  projectPath: app
              env:
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

            # The `artifacts` output can now be used by a different action to upload the artifacts
            - uses: actions/upload-artifact@v3
              with:
                  name: artifacts-${{ matrix.platform }}
                  path: "${{ join(fromJSON(steps.tauri_build.outputs.artifacts), '\n') }}"
