name: "CI"
on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    build-desktop:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev libxtst-dev libevdev-dev libxdo-dev

            - name: Cache Rust Dependencies
              uses: Swatinem/rust-cache@v2
              with:
                  shared-key: rust-deps
                  save-if: false

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: install frontend dependencies
              run: pnpm install

            - run: mkdir apps/desktop/dist

            - name: Build
              id: tauri_build
              run: |
                  pnpm desktop tauri build --ci
              env:
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

            - uses: actions/upload-artifact@v3
              with:
                  name: artifacts-${{ matrix.platform }}
                  path: ./target/release/bundle/*

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: install frontend dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test
    migrate-db:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              id: pnpm-install
              with:
                  version: 8
                  run_install: false

            - name: install frontend dependencies
              run: pnpm install

            - name: Migrate Database
              run: pnpm web db:deploy
