name: Publish Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'Brendonovich/MacroGraph'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE_NAME=ghcr.io/$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')/macrograph-server" >> $GITHUB_ENV

      - name: Determine tag
        id: determine-tag
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          echo "IMAGE_SHA=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          if [[ "${{ github.event_name }}" != "pull_request" ]]; then
            echo "TAG=main" >> $GITHUB_ENV
          fi

      - name: Report image SHA
        run: |
          echo "Image SHA: ${{ env.SHORT_SHA }}"
          echo "image-sha=${{ env.SHORT_SHA }}" >> $GITHUB_OUTPUT

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/server/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}${{ env.TAG != '' && format(' ${{ env.IMAGE_NAME }}:${{ env.TAG }}') || '' }}
