name: "Release Desktop"

on: workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    draft:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Create draft release
              uses: crabnebula-dev/cloud-release@v0.1.0
              with:
                  command: release draft ${{ secrets.CN_APP_ID }} --framework tauri
                  api-key: ${{ secrets.CN_API_KEY }}

    build:
        needs: draft
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v3

            - name: setup node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable

            - name: Install desktop deps
              uses: ./.github/actions/install-desktop-deps

            - name: Cache Rust Dependencies
              uses: Swatinem/rust-cache@v2
              with:
                  shared-key: rust-deps
                  save-if: false

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Install frontend dependencies
              run: pnpm install

            - name: Build Desktop
              run: pnpm desktop tauri build --ci
              env:
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
                  ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
                  APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
                  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
                  APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
                  APPLE_PROVIDER_SHORT_NAME: ${{ secrets.APPLE_PROVIDER_SHORT_NAME }}
                  APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
                  APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}

            - name: Upload assets to CrabNebula Cloud
              uses: crabnebula-dev/cloud-release@v0.1.0
              with:
                  command: release upload ${{ secrets.CN_APP_ID }} --framework tauri
                  api-key: ${{ secrets.CN_API_KEY }}

    publish:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4

            - name: Publish release
              uses: crabnebula-dev/cloud-release@v0.1.0
              with:
                  command: release publish ${{ secrets.CN_APP_ID }} --framework tauri
                  api-key: ${{ secrets.CN_API_KEY }}
