name: "Release Desktop"

on: workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    draft:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - uses: actions/checkout@v4

            - name: Create draft release
              uses: crabnebula-dev/cloud-release@v0.1.0
              with:
                  command: release draft ${{ secrets.CN_APP_ID }} --framework tauri ${{ github.ref_name }}
                  api-key: ${{ secrets.CN_API_KEY }}

    build:
        needs: draft
        strategy:
            fail-fast: false
            matrix:
                settings:
                    - host: macos-latest
                      target: x86_64-apple-darwin
                    - host: macos-latest
                      target: aarch64-apple-darwin
                    - host: windows-latest
                      target: x86_64-pc-windows-msvc
                    - host: ubuntu-latest
                      target: x86_64-unknown-linux-gnu

        runs-on: ${{ matrix.settings.host }}
        steps:
            - uses: actions/checkout@v3

            - uses: apple-actions/import-codesign-certs@v2
              if: ${{ runner.os == 'macOS' }}
              with:
                  p12-file-base64: ${{ secrets.APPLE_CERTIFICATE }}
                  p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}

            - uses: ./.github/actions/setup-js

            - uses: ./.github/actions/setup-rust

            - uses: ./.github/actions/install-desktop-deps

            - name: Build Desktop
              run: pnpm desktop tauri build --ci --target ${{ matrix.settings.target }}
              env:
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
                  ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
                  APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
                  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
                  APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
                  APPLE_PROVIDER_SHORT_NAME: ${{ secrets.APPLE_PROVIDER_SHORT_NAME }}
                  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

            - name: Upload assets to CrabNebula Cloud
              uses: crabnebula-dev/cloud-release@v0.1.0
              with:
                  command: release upload ${{ secrets.CN_APP_ID }} --framework tauri ${{ github.ref_name }}
                  api-key: ${{ secrets.CN_API_KEY }}

    publish:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v4

            - name: Publish release
              uses: crabnebula-dev/cloud-release@v0.1.0
              with:
                  command: release publish ${{ secrets.CN_APP_ID }} --framework tauri ${{ github.ref_name }}
                  api-key: ${{ secrets.CN_API_KEY }}
