name: "Release Desktop"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_VERSION_FILE: apps/desktop/package.json

jobs:
  draft:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.read_version.outputs.version }}
      needs_release: ${{ steps.create_tag.outputs.tag_existed != 'true' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Read version number
        id: read_version
        run: |
          VERSION=$(node -p "require('./${{ env.APP_VERSION_FILE }}').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create tag
        id: create_tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = "${{ steps.read_version.outputs.version }}";
            const tagRef = `tags/${tag}`;

            const TAG_EXISTED = "tag_existed";

            async function main() {
              let tagExisted = true;

              try {
                await github.rest.git.getRef({
                  ref: tagRef,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });

                tagExisted = true;
                core.notice(`Release skipped as tag '${tag}' already exists. Update the version in '${{ env.APP_VERSION_FILE }}' to perform a release.`);
              } catch (error) {
                if ("status" in error && error.status === 404) tagExisted = false;
                else throw error;
              }

              core.setOutput(TAG_EXISTED, tagExisted);

              if (!tagExisted)
                await github.rest.git.createRef({
                  ref: `refs/${tagRef}`,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  sha: context.sha,
                });
            }

            main();

  build:
    needs: draft
    if: ${{ needs.draft.outputs.needs_release == 'true' }}
    runs-on: ${{ matrix.settings.host }}
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: mac
            arch: x64
          - host: macos-latest
            target: mac
            arch: arm64
          - host: windows-latest
            target: win
            arch: x64
          - host: ubuntu-latest
            target: linux
            arch: x64
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-js

      - name: Build Desktop
        run: pnpm build:app
        working-directory: apps/desktop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.settings.target }}-${{ matrix.settings.arch }}
          path: apps/desktop/release/**/*
